[package]
name = "kfs-1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
spin = "0.9.8"
multiboot2-header = { version = "0.4.0", default-features = false }
x86_64 = "0.15.1"
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
