[package]
name = "kfs-1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.5.2"
multiboot2 = "0.20.2"
x86_64 = "0.15.1"
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
